config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords:     'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    # omniauth_callbacks: 'users/omniauth_callbacks',
  }
  root 'tops#index'
  resources :users, only: [:index, :edit, :update, :show] do
    collection do
      get :logout
    end
  end
  resources :tops, only: [:index, :new, :create, :show, :edit, :update, :destroy] 

  resources :tops do
    member do
      get 'see'
      patch 'buy'
      get 'buyed'
    end
  end


end

app/views/shared/_application.html.haml
.application
  =image_tag("slide.png", width:"1450")

app/views/shared/_footer.html.haml
.footer
  .footer-top
    .footer-top-mercaris
      .footer-top-merucari
        メルカリについて
        .footer-top-merucari-box
          .footer-top-merucari-box__li
            会社概要（運営会社）
          .footer-top-merucari-box__li
            採用情報
          .footer-top-merucari-box__li
            プレスリリース
          .footer-top-merucari-box__li
            公式ブログ
          .footer-top-merucari-box__li
            メルカリロゴ利用ガイドライン
      .footer-top-merucari__twitter
        =fa_icon'twitter' , class: 'icon'
      .footer-top-merucari__facebook
        =fa_icon'facebook' , class: 'icon'

    .footer-top-helps
      .footer-top-help
        ヘルプ＆ガイド
        .footer-top-help-box
          .footer-top-help-box__li
            メルカリガイド
          .footer-top-help-box__li
            らくらくメルカリ便
          .footer-top-help-box__li
            ゆうゆうメルカリ便
          .footer-top-help-box__li
            大型メルカリ便
          .footer-top-help-box__li
            車体取引ガイド
          .footer-top-help-box__li
            メルカリあんしん・あんぜん宣言
          .footer-top-help-box__li
            偽ブランド品撲滅への取り組み
          .footer-top-help-box__li
            メルカリボックス
    .footer-top-privacys
      .footer-top-privacy
        プライバシーと利用規約
        .footer-top-privacy-box
          .footer-top-privacy-box__li
            プライバシーポリシー
          .footer-top-privacy-box__li
            メルカリ利用規約
          .footer-top-privacy-box__li
            あんしんスマホサポート制度に関する利用規約
          .footer-top-privacy-box__li
            コンプライアンスポリシー
      .footer-top-private
        .footer-top-private-box
          .footer-top-private-box__li
            個人データの安全管理に関わる基本方針
          .footer-top-private-box__li
            特定商取引に関する表記
          .footer-top-private-box__li
            資金決済法に基づく表示
          .footer-top-private-box__li
            法令遵守と犯罪の抑止のために
          .footer-top-private-box__li
            返品・返金のポリシー
    .footer-top-country
      国
      .footer-top-country__li
        日本
        .footer-top-country__li
          United States
  .footer-under
    = link_to image_tag("blacklogo.png", width:"150"), root_path

app/views/shared/_header.html.haml
.header
  .header-top
    .header-logo
      = link_to image_tag("logo.png",width:"150"), root_path
    .header-surch-bar
      何かお探しですか？
      .header-surch-bar__icon
        =fa_icon'search' , class: 'icon'
  .header-under
    .header-under-left
      .header-under-left-category
        カテゴリから探す
        .header-under-left-category__icon
          =fa_icon'list-ul' , class: 'icon'
      .header-under-left-bland
        ブランドから探す
        .header-under-left-bland__icon
          =fa_icon'tag', class: 'icon'
    .header-under-right
      - if user_signed_in?
        .header-under-right-news
          .header-under-right-news__icon
            =fa_icon 'bell-o' , class: 'icon'
          .header-under-right-news__button お知らせ
        .header-under-right-todo
          .header-under-right-todo__icon
            =fa_icon 'check' , class: 'icon'
          .header-under-right-todo__button やることリスト
        .header-under-right-mypage
          .header-under-right-mypage__icon
            =fa_icon 'smile-o' , class: 'icon'
          .header-under-right-mypage__button
            = link_to "マイページ", user_path(current_user.id), id: 'mypage-link'
      - else
        .header-under-right-login
          .header-under-right-login__button
            = link_to "ログイン", new_user_session_path, id: 'login-btn'
          .header-under-right-new
            .header-under-right-new__button
              = link_to "新規会員登録", new_user_registration_path, id: 'new-btn'

app/views/shared/_mypage-sidebar.html.haml
.mypage
  .mypage__side-bar
    .mypage__side-bar__list
      .mypage__side-bar__list__box
        .mypage__side-bar__list__box__mypage
          = link_to "マイページ", user_path(current_user.id), id: 'mypage-link'
        .mypage__side-bar__list__box__news お知らせ
        .mypage__side-bar__list__box__todo やることリスト
        .mypage__side-bar__list__box__good いいね！一覧
        .mypage__side-bar__list__box__exhibition
          = link_to "出品する", new_top_path, id: 'exhibition-link'
        .mypage__side-bar__list__box__display 出品した商品-出品中
        .mypage__side-bar__list__box__exhibition-trade 出品した商品-取引中
        .mypage__side-bar__list__box__sold 出品した商品-売却済み
        .mypage__side-bar__list__box__exhibition-buy 購入した商品-取引中
        .mypage__side-bar__list__box__news-list ニュース一覧
        .mypage__side-bar__list__box__evaluate-list 評価一覧
        .mypage__side-bar__list__box__guide ガイド
        .mypage__side-bar__list__box__contact お問い合わせ
    .mypage__side-bar__marpay
      .mypage__side-bar__marpay__box
        .mypage__side-bar__marpay__box__label メルペイ
        .mypage__side-bar__marpay__box__sale-transfer 売上・振込申請
        .mypage__side-bar__marpay__box__point ポイント
    .mypage__side-bar__setting
      .mypage__side-bar__setting__box
        .mypage__side-bar__setting__box__label 設定
        .mypage__side-bar__setting__box__profile プロフィール
        .mypage__side-bar__setting__box__change-adress 発送元・お届け先住所変更
        .mypage__side-bar__setting__box__payment 支払い方法
        .mypage__side-bar__setting__box__email-password メール/パスワード
        .mypage__side-bar__setting__box__user-info
          = link_to "本人情報", edit_user_registration_path, id: 'edit_link'
        .mypage__side-bar__setting__box__telephone-number 電話番号の確認
        .mypage__side-bar__setting__box__sign-out
          = link_to "ログアウト", logout_users_path, id: 'logout_link'
  